# Step 4:

# This step requires the Buildbot git repository to contain buildbot remote that points to https://github.com/buildbot/buildbot and can be pushed to.
# Additionally, the Buildbot docs repository (https://github.com/buildbot/bbdocs) must be checked out at ../bbdocs path.
# Pull the merge commit created on the master branch during the step 2. Then run:
# make release VERSION=x.y.z
# This will create the required tags, make documentation, copy it to bbdocs repo and push everything.

name: Perform Release

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      version:
        description: "Release version x.y.z"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    # This step only needs to run if it's a merged release notes PR or a manual dispatch.
    if: >
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'Release Notes for Version')) 
      || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
        with:
          path: buildbot
      - name: Read repository configuration
        working-directory: ./buildbot
        id: var
        run: |
          content=`cat .github/repo_config.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=repo_config::$content"
      - uses: actions/checkout@v3
        with:
          repository: ${{ fromJson(steps.var.outputs.repo_config).owner }}/bbdocs
          fetch-depth: 0
          path: bbdocs
          token: ${{ secrets.BBDOCS_PAT }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Setup version
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "VERSION=$(echo ${{ github.event.pull_request.title }} | cut -d' ' -f5)" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi
      - name: Install dependencies
        working-directory: ./buildbot
        run: |
          pip install -U pip setuptools wheel
          pip install -r requirements-ci.txt -r requirements-cidocs.txt
          pip install towncrier virtualenv sphinx
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          workdir: ./buildbot
      - name: Perform release
        working-directory: ./buildbot
        run: |
          git config --global user.name github-actions
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add buildbot https://github.com/${{ fromJson(steps.var.outputs.repo_config).owner }}/${{ fromJson(steps.var.outputs.repo_config).repo }}.git
          make release VERSION=$VERSION
